language: objective-c
osx_image: xcode7.1
env:
 global:
    - "MODULE_NAME=ti.urlsession" 
before_install:
    - MODULE_ROOT=$PWD
install:
    - cd $MODULE_ROOT
    - curl -o install.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/install.sh
    - source install.sh -s "--branch 5_1_X"
script:
    - cd ios/ti.urlsession
    - ./build.py
    - curl -o script.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/script.sh    
    - source script.sh
    - mkdir -p "$MODULE_ROOT/s3"
    - NOW=$(date +"%Y%m%d%H%M")
    - echo "cp -p \"${MODULE_NAME}-iphone-${MODULE_VERSION}.zip\" \"${MODULE_ROOT}/s3/${MODULE_NAME}-iphone-${MODULE_VERSION}-${TRAVIS_BRANCH}-${NOW}.zip\""
    - cp -p "${MODULE_NAME}-iphone-${MODULE_VERSION}.zip" "${MODULE_ROOT}/s3/${MODULE_NAME}-iphone-${MODULE_VERSION}-${TRAVIS_BRANCH}-${NOW}.zip"
deploy:
  provider: s3
  access_key_id: AKIAJEU4ONO4EVCH6DRA
  secret_access_key:
    secure: DjoNYXNIjuURlV+tIXBJtaL6sZGI46OgT2IkYfk/iETBTz6QUUQnPcvkMjcl63TjVPKlcxwDswAy/iu7+vSg/VTZLk22PTGksPLJf/fV0BNnqlDWpBh8SIcdxoly0Kmwmf41KLG9lI/8IEi1zOL/x/qbA1nKN72RgiXmLISgFjM=
  upload-dir: modules/ti.urlsession
  bucket: builds.appcelerator.com
  local-dir: $TRAVIS_BUILD_DIR/s3/
  skip_cleanup: true
  on:
    repo: appcelerator-modules/ti.urlsession
    branch: master